CREATE ROLE readers WITH NOLOGIN;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readers;
CREATE USER user01 WITH PASSWORD 'password';
GRANT readers TO user01;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
